// frontend/src/components/AccentPicker.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import { Palette } from "lucide-react";
import { cn } from "@/lib/utils";

const COOKIE_KEY = "kura-accent-hue";
const STORAGE_KEY = "kura-accent-hue";
const DEFAULT_HUE = 175;
const HUE_EVENT = "kura-accent-change";

function applyHue(hue: number) {
  document.documentElement.style.setProperty("--accent-hue", String(hue));
  document.documentElement.style.setProperty("--accent-hue-end", String(hue + 25));
}

function persistHue(hue: number) {
  // Cookie — readable by SSR so the next page load has the right hue before paint
  document.cookie = `${COOKIE_KEY}=${hue}; path=/; max-age=31536000; samesite=lax`;
  // localStorage — fallback for same-page reads and older browsers
  try { localStorage.setItem(STORAGE_KEY, String(hue)); } catch {}
}

function readHue(): number | null {
  // Prefer localStorage (immediate, no parsing), fall back to cookie
  try {
    const ls = localStorage.getItem(STORAGE_KEY);
    if (ls) {
      const v = parseInt(ls, 10);
      if (!isNaN(v) && v >= 0 && v <= 360) return v;
    }
  } catch {}
  const match = document.cookie.match(new RegExp(`(?:^|; )${COOKIE_KEY}=([^;]*)`));
  if (match) {
    const v = parseInt(match[1], 10);
    if (!isNaN(v) && v >= 0 && v <= 360) return v;
  }
  return null;
}

export default function AccentPicker() {
  const [hue, setHue] = useState(DEFAULT_HUE);
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const debounceRef = useRef(0);

  useEffect(() => {
    const stored = readHue();
    if (stored != null) {
      setHue(stored);
      applyHue(stored);
    }

    function handleHueChange(event: Event) {
      const next = Number((event as CustomEvent<number>).detail);
      if (Number.isNaN(next)) return;
      setHue(next);
      applyHue(next);
    }

    window.addEventListener(HUE_EVENT, handleHueChange as EventListener);
    return () =>
      window.removeEventListener(HUE_EVENT, handleHueChange as EventListener);
  }, []);

  useEffect(() => {
    if (!open) return;
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("click", handler);
    return () => document.removeEventListener("click", handler);
  }, [open]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const val = parseInt(e.target.value, 10);
    setHue(val);
    applyHue(val);
    window.dispatchEvent(new CustomEvent<number>(HUE_EVENT, { detail: val }));
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      persistHue(val);
    }, 150);
  }, []);

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen(!open)}
        className={cn(
          "flex items-center justify-center",
          "w-9 h-9 rounded-[var(--radius-sm)]",
          "transition-all duration-[var(--duration-fast)]",
          "hover:bg-[var(--accent-subtle)]",
          "focus-visible:ring-2 focus-visible:ring-[var(--accent-color)] focus-visible:ring-offset-2",
          "active:scale-[0.85]"
        )}
        aria-label="选择强调色"
        title="色调"
      >
        <Palette
          className="w-4 h-4 transition-colors duration-[var(--duration-fast)]"
          style={{ color: `oklch(72% 0.12 ${hue})` }}
        />
      </button>
      {open && (
        <div
          className={cn(
            "absolute right-0 top-full mt-1.5",
            "p-3 rounded-[var(--radius-md)]",
            "border border-[var(--border-color)]",
            "bg-[var(--bg-surface)] shadow-lg",
            "z-50 flex flex-col gap-2",
            "min-w-[180px]"
          )}
          style={{ animation: "dropIn var(--duration-normal) var(--ease-out)" }}
        >
          <span className="text-[11px] text-[var(--text-muted)] font-medium">
            色调 {hue}°
          </span>
          <input
            type="range"
            min={0}
            max={360}
            value={hue}
            onChange={handleChange}
            className="w-full h-2 rounded-full appearance-none cursor-pointer"
            style={{
              background: `linear-gradient(to right, 
                hsl(0, 80%, 55%), 
                hsl(30, 80%, 55%), 
                hsl(60, 80%, 50%), 
                hsl(120, 70%, 45%), 
                hsl(180, 70%, 45%), 
                hsl(240, 70%, 55%), 
                hsl(300, 70%, 55%), 
                hsl(360, 80%, 55%))`,
              accentColor: `oklch(72% 0.12 ${hue})`,
            }}
          />
        </div>
      )}
    </div>
  );
}

// app/components/AccentPicker.vue
<script setup lang="ts">
const accentCookie = useCookie('kura-accent-hue')
const currentHue = ref(parseInt(accentCookie.value || '', 10) || 175)
const showSlider = ref(false)
let persistTimer: ReturnType<typeof setTimeout> | null = null

function updateHue(value: number) {
  currentHue.value = value
  document.documentElement.style.setProperty('--accent-hue', String(value))
  document.documentElement.style.setProperty('--accent-hue-end', String(value + 25))
}

function onSliderChange(e: Event) {
  const value = Number((e.target as HTMLInputElement).value)
  updateHue(value)
  if (persistTimer) clearTimeout(persistTimer)
  persistTimer = setTimeout(() => {
    accentCookie.value = String(value)
    localStorage.setItem('kura-accent-hue', String(value))
    window.dispatchEvent(new CustomEvent('kura-accent-change', { detail: { hue: value } }))
  }, 150)
}

let clickOutsideHandler: ((e: MouseEvent) => void) | null = null

onMounted(() => {
  clickOutsideHandler = (e: MouseEvent) => {
    const target = e.target as HTMLElement
    if (!target.closest('[data-accent-picker]')) showSlider.value = false
  }
  document.addEventListener('click', clickOutsideHandler)
})

onUnmounted(() => {
  if (clickOutsideHandler) document.removeEventListener('click', clickOutsideHandler)
  if (persistTimer) clearTimeout(persistTimer)
})
</script>

<template>
  <div class="relative flex items-center justify-center group" data-accent-picker>
    <button
      type="button"
      @click="showSlider = !showSlider"
      class="w-9 h-9 rounded-[var(--radius-sm)] flex items-center justify-center transition-all hover:bg-[var(--accent-subtle)] active:scale-85"
      aria-label="选择强调色"
      title="强调色"
    >
      <!-- Palette icon -->
      <svg class="w-[18px] h-[18px] text-[var(--text-muted)] hover:text-[var(--accent-color)] transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10a2 2 0 0 0 2-2c0-.52-.2-1.01-.57-1.38-.37-.36-.57-.86-.57-1.38 0-1.1.9-2 2-2 4.43 0 8-3.58 8-8 0-5.51-4.49-10-10-10Z" />
        <circle cx="7.5" cy="11.5" r="1.5" fill="currentColor" stroke="none" />
        <circle cx="12" cy="7.5" r="1.5" fill="currentColor" stroke="none" />
        <circle cx="16.5" cy="11.5" r="1.5" fill="currentColor" stroke="none" />
      </svg>
    </button>
    <div
      v-if="showSlider"
      class="absolute top-full right-0 mt-2 p-3 rounded-[var(--radius-md)] bg-[var(--bg-surface)] border border-[var(--border-color)] shadow-lg z-50"
      @click.stop
    >
      <div class="text-xs text-[var(--text-muted)] text-center mb-2">色调 {{ currentHue }}°</div>
      <input
        type="range" min="0" max="360" :value="currentHue"
        @input="onSliderChange"
        class="w-32 h-2 rounded-full appearance-none cursor-pointer accent-[var(--accent-color)]"
        :style="{ background: `linear-gradient(to right, hsl(0,70%,50%),hsl(30,70%,50%),hsl(60,70%,50%),hsl(120,70%,50%),hsl(180,70%,50%),hsl(240,70%,50%),hsl(300,70%,50%),hsl(360,70%,50%))` }"
      />
    </div>
  </div>
</template>
